from nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

run apt-get update && apt-get install -y \
python3-pip

#run pip3 install \
#tensorboard==2.2.1 \
#pytorch-lightning==0.7.6 \
#torch==1.5.0 \
#torchvision

run pip3 install \
tensorboard \
pytorch-lightning \
torch \
torchvision

run ln -s /mounted/data /data
